[project]
name = "tubes3-u-tiga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymysql>=1.1.1",
    "pyqt6==6.7.0",
    "mysql-connector-python>=8.0.35",
    "pymupdf>=1.26.1",
]
